sudo: required

services:
  - docker

before_script:
  - docker-compose build

script:
  - docker-compose run --rm app
  - docker pull quay.io/keboola/developer-portal-cli-v2:latest
  - export REPOSITORY=`docker run --rm -e KBC_DEVELOPERPORTAL_USERNAME -e KBC_DEVELOPERPORTAL_PASSWORD quay.io/keboola/developer-portal-cli-v2:latest ecr:get-repository $KBC_DEVELOPERPORTAL_VENDOR $KBC_DEVELOPERPORTAL_APP`
  - docker tag $KBC_APP_REPOSITORY:latest $REPOSITORY:master
  - eval $(docker run --rm -e KBC_DEVELOPERPORTAL_USERNAME -e KBC_DEVELOPERPORTAL_PASSWORD quay.io/keboola/developer-portal-cli-v2:latest ecr:get-login $KBC_DEVELOPERPORTAL_VENDOR $KBC_DEVELOPERPORTAL_APP)
  - docker push $REPOSITORY:master
  # Run live test job on new master image
  # env requires: KBC_STORAGE_TOKEN and KBC_APP_TEST_CONFIG (a token to a test project where the app has a configuration)
  - docker pull quay.io/keboola/syrup-cli:latest
  - docker run --rm -e KBC_STORAGE_TOKEN quay.io/keboola/syrup-cli:latest run-job $KBC_DEVELOPERPORTAL_APP 288077272 master
  - docker run --rm -e KBC_STORAGE_TOKEN quay.io/keboola/syrup-cli:latest run-job $KBC_DEVELOPERPORTAL_APP 288085574 master
  - docker run --rm -e KBC_STORAGE_TOKEN quay.io/keboola/syrup-cli:latest run-job $KBC_DEVELOPERPORTAL_APP 313753900 master

after_success:
  - docker images

after_error:
  - docker-compose logs

after_failure:
  - docker-compose logs

deploy:
  provider: script
  skip_cleanup: true
  script: "./deploy.sh"
  on:
    tags: true

notifications:
  email: false
  slack:
    secure: HE/zGZqyccq3n9eKL/eCDV1ZCSZOyw66g8pyGwm5QsicjKsCt+x3GfW79pk7wPAoQyIsApyT8LI2wxpAEFz4GvXkyQI0lc/hs6dnnXAMfddAMM8vWEmwZiXShd3j3o0gRdyqaVKgf6IbJvohPG4zqMyt2ZDVk6NkutVqBWo23rU71TbxovdW9l9pTEMbEiJHDhtS5pCAE8utAmao8PN1/Q4GeqAyK+zd6etUD06cidWOr1ImWOANShPKSJvDoxd68+wG+fEGAoSIZa80ImluxYrXGqstS8WMbp2HEhYhJ4wLJS3gXulB5skdQD0v1KhHNc7B4+0BQQftLtgamnaOD+lUeRv1sp2vXmcAecLxRyKyByXoOpPd/k1jfPo8n6IfoZeJEsEfbHW9AGXi95q2xImEZZi2T/KGsthuJdz+I7rfvu2X/J5ayn7bFbWeW9zdiFdv+P44bcidK+m3qd34QQtSRiHm1gRgLk+axZShuxIOzPONwMQl6AAZw+BsGSJYqs/KbbZjDJBHttMeOTg+ikgcYXQFbKMfjsDTDSiUkDsjZ9O4Qg7VcHB6Fxdg6rL09qblT2AVoddzMLMhdv8EUqX1pgLwlvQc1rQM3vHfmNSmkOLrCx4V6f8QuSjZRr2TQSAI9ZaMUm4+iOan5LduWvyVT4xtKWDcywE5JuszVc8=
